### ISSUE TITLE
New version release is broken :(

### ISSUE THREAD

**Issue by notmgsk** [rigetti/quil-rs#123]
The latest `quil-rs` version on [crates.io is v0.14.1](https://crates.io/crates/quil-rs). The version specified in `Cargo.toml` is `0.10.0`, which happened in a recent merge which _should have_ bumped the version to 0.15.0. 

Not really sure how it got into this pickle, but it's something we should fix before it gets us into trouble.

Changing `Cargo.toml`'s version to `0.14.1` and running `knope --dry-run prerelease` shows the version would be bumped to `0.11.0`, so that's not the issue...

(Paging the wise and wonderful @dbanty just in case they can spare a few minutes for their old friends.)

**Comment by kalzoo** [comment]
Would we not expect pushing an updated `Cargo.toml` and tag onto `main` to fix this?

**Comment by notmgsk** [comment]
> Would we not expect pushing an updated `Cargo.toml` and tag onto `main` to fix this?

Tried it locally without success.

**Comment by dbanty** [comment]
> As part of resolving this issue, though, we should make sure the release rule actually calls the Release action -- it does not currently (prerelease has one more step than release does).

You may be able to switch to `--prerelease-label` now to unify those rules.

Sorry I didn't get your summons @notmgsk, not sure why a mention didn't land in my notifications 🤔. Thanks for contributing a fix though, folks. I'll have that new version out soon.

Miss you 💜

**Comment by MarquessV** [comment]
Fixed in #166
