### ISSUE TITLE
Python Bindings: Program.expand_calibrations & Program.into_simplified

### ISSUE THREAD

**Issue by kalzoo** [rigetti/quil-rs#157]
Per [this comment](https://github.com/rigetti/quil-rs/pull/156#discussion_r1132814605):

Consumers of the Python bindings should be able to expand calibrations within a program, as well as simplify that program (removing unused calibrations, etc). Both of these are available today within `quil-rs` and are commonly useful.

Use cases:

- Several pyQuil consumers currently expand calibrations within a program one-by-one using helper scripts; the changes in pyQuil v4 may make that harder, so we can make up for that by vending a method to do that expansion for them. It's easy to get the calibration expansion logic wrong, so it's useful to allow customers to share that code.
- Program simplification can reduce load on our services and improve translation response time by reducing request body size. `pyQuil` v4 can and should simplify programs prior to transmission to QCS for a better user experience.

**Comment by MarquessV** [comment]
[This has been done](https://github.com/rigetti/quil-rs/blob/main/quil-py/src/program/mod.rs#L181-L195)
