### ISSUE TITLE
Support RESET Instructions

### ISSUE THREAD

**Issue by kalzoo** [rigetti/quil-rs#33]
`RESET` instructions are properly parsed, but their "used frames" are computed as `None`. This is incorrect - a `RESET` acts on the following frames:

1. If a qubit is specified, it acts on frames which use exactly that qubit, and blocks all frames which intersect that qubit
2. If no qubit is specified, apply rule # 1 to all qubits used in the program.

This is an over-simplification in that the implementation of `RESET` is backend-dependent and thus may act on a smaller number of frames than described here. However, this model will allow the timing of a user's program to be properly modeled on the client side.

**Comment by genos** [comment]
Isn't this closed by #129?

**Comment by kalzoo** [comment]
you bet, @genos
