### ISSUE TITLE
[STUB] talk to physicists about revising program-fidelity logic

### ISSUE THREAD

**Issue by BatmanAoD** [rigetti/quil-rs#335]
Currently, `quilc` computes the program-fidelity using the following formula (and soon, the analysis package will implement the same logic):

```
e^(-sqrt(sum(log(fidelity)^2)))
```

...where `sum(...fidelity...)` indicates the sum over all gate fidelities for the given program.

This treats all gates as independent and gives them equal impact on the final fidelity metric. It is not clear that this is the correct approach; it may be preferable to choose a different definition.

For instance, we could compute a fidelity metric along each `lschedule` "path" (where a "path" is the sequence of gates and `measure`s using a specific qubit) by simply multiplying the fidelities along that path, then taking the minimum fidelity from that set, or perhaps applying the above algorithm to these "path fidelities".

**Comment by kalzoo** [comment]
From internal discussion, this is best left to dedicated benchmarking libraries, because a useful fidelity score is highly dependent on context
