### ISSUE TITLE
Remove dependency on `lexical`

### ISSUE THREAD

**Issue by BatmanAoD** [rigetti/quil-rs#337]
There are soundness issues in the `lexical` crate. This warning from `deny` includes explanations of the soundness issues and recommendations for how to get similar functionality without the `lexical` crate.

From a brief look at the code, it appears that we only use the `lexical` crate to format floating-point numbers; however, the `deny` recommendation does not recommend anything for this use-case. One crate that may provide what we need is [numfmt](https://crates.io/crates/numfmt).

> warning[unsound]: Multiple soundness issues
> ```
>    ┌─ /github/workspace/Cargo.lock:70:1
>    │
> 70 │ lexical 6.1.1 registry+https://github.com/rust-lang/crates.io-index
>    │ ------------------------------------------------------------------- unsound advisory detected
>    │
> ```
>    = ID: RUSTSEC-2023-0055
>    = Advisory: https://rustsec.org/advisories/RUSTSEC-2023-0055
>    = `lexical` contains multiple soundness issues:
>      
>    1. [Bytes::read() allows creating instances of types with invalid bit patterns](https://github.com/Alexhuszagh/rust-lexical/issues/102)
>    2. [BytesIter::read() advances iterators out of bounds](https://github.com/Alexhuszagh/rust-lexical/issues/101)
>    3. [The `BytesIter` trait has safety invariants but is public and not marked `unsafe`](https://github.com/Alexhuszagh/rust-lexical/issues/104)
>    4. [`write_float()` calls `MaybeUninit::assume_init()` on uninitialized data, which is is not allowed by the Rust abstract machine](https://github.com/Alexhuszagh/rust-lexical/issues/95)
>      
>  The crate also has some correctness issues and appears to be unmaintained.
>     
>  ## Alternatives
>      
>  For quickly parsing floating-point numbers third-party crates are no longer needed. A fast float parsing algorith by the author of `lexical` has been [merged](https://github.com/rust-lang/rust/pull/867[61](https://github.com/rigetti/quil-rs/actions/runs/7778832009/job/21209068238#step:4:62)) into libcore.
>      
>  For quickly parsing integers, consider `atoi` and `btoi` crates (100% safe code). `atoi_radix10` provides even faster parsing, but only with `-C target-cpu=native`, and at the cost of some `unsafe`.
>      
>  For formatting integers in a `#[no_std]` context consider the [`numtoa`](https://crates.io/crates/numtoa) crate.
>      
>  For working with big numbers consider `num-bigint` and `num-traits`.

**Comment by Shadow53** [comment]
For more context, [this](https://github.com/rigetti/quil-rs/blob/f717bc1d8105c8f28ab781823e0f7d80138eac93/quil-rs/src/expression/mod.rs#L465) appears to be the only function that uses `lexical`, so it should be fairly straightforward to replace
