### ISSUE TITLE
Bug in Timing/Frame Dependencies

### ISSUE THREAD

**Issue by kalzoo** [rigetti/quil-rs#75]
Hot on the heels of #73 , another bug has been found in how frame blocking is calculated. Two examples are given here, with further explanation below. Can you spot the bug?

# Example 1

Hint: there is an additional frame defined in the program, `0 1 "cz"`, which is not used by any of the instructions.

![graphviz (4)](https://user-images.githubusercontent.com/22137047/171543529-b1e77748-23aa-43f3-b961-dd5375457284.svg)

# Example 2

![graphviz (5)](https://user-images.githubusercontent.com/22137047/171544044-053e40ae-0355-4f36-a496-1f21bde71fc9.svg)

The problem here is that the change in #73 properly fixed how dependencies are calculated _after_ a blocking instruction, but that blocking instruction _must itself block on previous instructions which overlap in frames_, and that is not happening.

Specifically/formally:

1. An instruction which _uses_ a frame must depend on the most-recent _user_ **and** _blockers_ of the frame, if any. Doing so clears all blockers of the frame and this instruction becomes the most-recent user.
2. An instruction which _blocks_ but does not _use_ a frame must depend on the most-recent user of the frame. Doing so leaves the most-recent user in place and adds this instruction to a list of most-recent blockers.

Blocking prevents simultaneous use but allows simultaneous blocking.

This approach is akin to a single-writer, multiple-reader lock or queue, where blocking:reading::using:writing.

**Comment by notmgsk** [comment]
Just seeing if I understand the issue:
* In example 1, the problem is the frame dependency between the `start` and `[1] PULSE 1 "rf"` nodes?
* In example 2, the problem is the missing frame dependency between nodes `[1]` and `[3]`?

**Comment by kalzoo** [comment]
Example 1 - yep. Example 2 - close! Dependency missing between 1 & 2

**Comment by notmgsk** [comment]
Oh -- 2 is related to your issue with the quil-spec?

**Comment by notmgsk** [comment]
Admittedly, I didn't think of that problem because I have come to see `NONBLOCKING` as having an effect on the following instructions.

**Comment by kalzoo** [comment]
> Oh -- 2 is your issue with the quil-spec?

It’s similar but not quite the same because they do in fact share the used frame. (That being said, I think that might have been a typo in building this example, so in reality yes that might be what I meant to illustrate).
