### ISSUE TITLE
Vend public parser for MemoryReference and Expression

### ISSUE THREAD

**Issue by kalzoo** [rigetti/quil-rs#96]
In the course of program execution with the Rust SDK, there's a need to be able to parse and interpret a memory reference, such as `ro[0]`. While this can be done with some simple string manipulation, it would be less brittle to use our purpose-built Quil parser.

However, this library does not offer an entrypoint to parse a memory reference on its own. `pyQuil` solves this problem for expressions by inserting the string-to-be-parsed into a gate instruction, parsing _that_ as a program, and then extracting the expression value ... but this is inelegant.

AC: this library exports functions allowing for the parsing of MemoryReference and Expression from strings. These should be all-consuming and not allow for leftovers. IMO, this would be best done using `FromStr`.

**Comment by jselig-rigetti** [comment]
`Expression::from_str` already exists: https://github.com/rigetti/quil-rs/blob/main/src/expression.rs#L414-L421
